### ISSUE TITLE
Sunny Boy SB3.6-1AV-40 can't encode character u'\xe4'

### ISSUE THREAD

**Issue by kaluxx** [Froschie/sma-translate#1]
I have problems with that script running on the above device as follows:
 *pi@raspi4138:~/sma-translate $ python WebConnectCodes.py --sma_ip="xxx.xxx.xxx.xxx" --sma_pw="xxxxx" --nossl=True
Traceback (most recent call last):
  File "WebConnectCodes.py", line 188, in <module>
    pr_output(str(translate(objects[item][x])), nl=False)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 12: ordinal not in range(128)*

To me it looks like it already trying to resolve the response. Any clue? Thanks!

**Comment by Froschie** [comment]
Hello,
I suspect Python2 was used, which I did not consider. Small workaround for Python2 is now included.

**Comment by kaluxx** [comment]
Yes - you are right - the same command with 'python3' it works perfectly. 
Thank you!
With python (2.7.16) after pulling the latest version the issue now moved some lines to 191 with the same error message. 
So simply use *python3 WebConnectCodes.py *
